import { z } from 'zod';
const player=z.object({id:z.string().min(1),name:z.string().trim().min(1).max(160),ghin:z.string(),index:z.number().min(-10).max(54).nullable(),email:z.string(),phone:z.string(),active:z.boolean()});
const course=z.object({name:z.string(),rating:z.number().min(40).max(100),slope:z.number().int().min(55).max(155),par:z.array(z.number().int().min(3).max(6)).length(18),strokeIndex:z.array(z.number().int().min(1).max(18)).length(18).refine(a=>new Set(a).size===18),allowance:z.number().min(0).max(100)});
const round=z.object({id:z.string().min(1),season:z.string().min(1),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),firstTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),interval:z.number().int().min(1).max(60),instructions:z.string().max(300).optional(),attendees:z.array(z.string()),groups:z.array(z.object({id:z.string(),playerIds:z.array(z.string()).max(4),locked:z.boolean()})),participants:z.array(z.object({playerId:z.string(),index:z.number(),courseHandicap:z.number().int(),playingHandicap:z.number().int(),gross:z.number().int().min(1).max(360).nullable(),holes:z.array(z.number().int().min(1).max(20).nullable()).length(18)})),course:course.optional(),status:z.enum(['draft','paired','completed'])});
export const leagueSchema=z.object({season:z.string().min(1).max(40),seasons:z.array(z.string().min(1).max(40)).min(1),players:z.array(player).max(1000),rounds:z.array(round).max(10000),course}).superRefine((value,ctx)=>{
 const ids=value.players.map(p=>p.id),roundIds=value.rounds.map(r=>r.id);
 if(new Set(ids).size!==ids.length||new Set(roundIds).size!==roundIds.length)ctx.addIssue({code:'custom',message:'Duplicate player or round identifiers.'});
 if(!value.seasons.includes(value.season))ctx.addIssue({code:'custom',message:'The selected season is missing.'});
 for(const r of value.rounds){const paired=r.groups.flatMap(g=>g.playerIds);if(r.attendees.some(id=>!ids.includes(id))||new Set(r.attendees).size!==r.attendees.length||new Set(paired).size!==paired.length||paired.some(id=>!r.attendees.includes(id)))ctx.addIssue({code:'custom',message:'Invalid round attendance or pairings.'});}
});
export const updateSchema=z.object({league:leagueSchema,version:z.number().int().positive()});
